### ISSUE TITLE
Angel demo running

### ISSUE THREAD

**Issue by dkondagit** [BattleAxeVR/OK_Cloud_Streamer#6]
Hello!
Thank you for your streamer, it works nice!
As for now I'm playing around CloudXR. SteamVr works fine, but I'm not able to make Angel (https://docs.nvidia.com/cloudxr-sdk/usr_guide/cxr_test_server.html) work on my Quest3.
I saw that you've done a lot of testing with CloudXR 4.0 and maybe you was successful running it?
So I have AWS instance with CloudXR setup, I'm running CloudXRServerSample.exe and trying to connect to my server via OVR sample, but nothing happens.

Client log ends with

```
21:04:26.357 I  (OVR Client)  REFRESH CHANGED! API now returns display refresh as 90
21:04:26.943 I  (OVR Client)  Waiting for server...
21:04:27.610 I  (OVR Client)  Waiting for server...
21:04:28.278 I  (OVR Client)  Waiting for server...
21:04:28.945 I  (OVR Client)  Waiting for server...
21:04:29.612 I  (OVR Client)  Waiting for server...
21:04:30.279 I  (OVR Client)  Waiting for server...
21:04:30.945 I  (OVR Client)  Waiting for server...
21:04:31.612 I  (OVR Client)  Waiting for server...
21:04:32.279 I  (OVR Client)  Waiting for server...
21:04:32.756 I  (OVR Client)  APP_CMD_PAUSE
21:04:32.757 I  (OVR Client)  CALLING vrapi_LeaveVrMode()
```

I you were able to run Angel sample maybe you can point me to the right direction?
Thank you in advance!

**Comment by BattleAxeVR** [comment]
Hi, thanks for using it! This makes me happy. The CXR server direct integration is a big potential benefit to using CloudXR over other PC VR streaming solutions, even over local wifi. 

I tried it ages ago through the first build and had some difficulties connecting consistently, I often had to kill the server demo, or even reboot. 

I have CXR server-side code implemented in my game engine partly, where it gets to the point of connecting but I haven't gone any farther than that yet (passing in eye buffers from my game or consuming controller / hmd poses yet, let alone the non-controller data like eye-tracking and body tracking). So give me a few days to fix a few things on my end, and I'll be working on this.

My next upgrade is adding Quest IOBT support, and Quest Pro eye-tracking on the android side, then trying to pass that through the non-controller data API to the server. The easiest way is to just finish my direct server integration before I try to migrate it into openxr api layer plugins similar to VDXR / mbucchia's work for Virtual Desktop (actually I plan on simply forking his work or repurposing it). 

Anyway, the way I got it to connect was enabling the verbose logs on both the client and the server side and inspecting what was happening. 

Try using the [latest release](https://github.com/BattleAxeVR/OK_Cloud_Streamer/releases/tag/v0.6_beta) instead of the older OVR build, make sure the IP, res, refresh are all compatible with what the server expects. It may not work at 120 Hz, or even 90 Hz, as the default Hz on the OVR sample is still 72 I believe, so maybe their server demo app is hardcoded for that, who knows

**Comment by dkondagit** [comment]
Hello.
Ok, thank you. 
I didn’t succeed with the previous setups, but I’ll try to test the new one as quickly as possible.

**Comment by dkondagit** [comment]
Finally got it to work on both your build and the previous OVR build. The main problem apparently was in the Windows Firewall, which works fine with Steam VR, but do not allow connections to bare CloudXR server.
<img width="741" alt="Снимок экрана 2024-04-26 в 12 16 41" src="https://github.com/BattleAxeVR/OK_Cloud_Streamer/assets/19476790/1ecea220-e988-43c2-8410-2e6c4fd7f86e">

Thank you!

**Comment by BattleAxeVR** [comment]
Oh that's great! Thanks. Now I remember having to do that as well, I had forgotten. Good catch!

**Comment by elbadcode** [comment]
yeah you might need to add that to install instructions. My client kept failing to connect last I tried, gonna test the firewall setting now
